/**
 * gachaData.js — 轉蛋模擬的道具池資料
 * -----------------------------------------------------------------
 * 資料來源：官方「機率商品說明」頁面公告的機率，非玩家推測值。等級標示
 * S/A/B/C 為官方原始分級，數字為官方公布的中獎機率（已四捨五入取小數
 * 後兩位，故單一箱總和不一定剛好等於 100%，這是官方公告本身的特性，
 * 不是這裡的計算誤差）。
 *
 * 部分道具為角色性別鎖定的成對道具（例如男/女泳裝），官方表格只公布
 * 一份共用機率，並說明無法獲得該性別道具時會把機率均等分配到其他獎勵。
 * 模擬器沒有角色性別設定，因此把同一組男女版本合併成一個獎項，避免把
 * 同一份官方機率重複計算兩次。
 *
 * weight 直接採用官方公布的機率數字（不用剛好加總 100，抽取邏輯會自己
 * 按比例算）。之後有新一期轉蛋上架，比照這個結構加新的 box 進
 * GACHA_BOXES，gacha.js 的邏輯不用改。
 *
 * 2026-08-27 更新：換到 08/27～09/09 這一期，id 沿用舊的（gacha.js
 * 用 box.id 當模擬統計的 key），只換 period 跟 items。官方公告裡的
 * 「彗星碎片」兌換表仍是 S=10、A=5、B=3、C=1；部分道具不能換且碎片
 * 會過期，目前沒有對應到站上任何功能。
 *
 * 2026-08-20 新增：另一台「轉蛋機」（eventAdId=19046，官方頁面上就叫
 * 這個名字，不是主題名），跟閃亮彗星/璀璨彗星並存、不是取代，所以是
 * 新增一個 box 而不是沿用舊 id。101 個道具官方沒有分 S/A/B/C 稀有度，
 * items 不帶 rarity（跟皇家美容院那幾箱一樣）。
 * -----------------------------------------------------------------
 */
const GACHA_BOXES = [
  {
    id: "shining-comet",
    name: "閃亮彗星",
    period: "2026/08/27 09:00 ～ 2026/09/09 23:59",
    items: [
      { name: "巧克力兔耳朵", rarity: "A", weight: 1.50 },
      { name: "巧克力套裝(男)／巧克力套裝(女)", rarity: "A", weight: 1.40 },
      { name: "巧克力鞋", rarity: "A", weight: 1.60 },
      { name: "巧克力蝴蝶手環", rarity: "A", weight: 1.70 },
      { name: "巧克力攪拌棒", rarity: "A", weight: 1.20 },
      { name: "巧克力球餅乾", rarity: "A", weight: 1.60 },
      { name: "銀狼耳朵", rarity: "B", weight: 1.80 },
      { name: "銀狼的戰鬥服", rarity: "B", weight: 1.90 },
      { name: "銀狼的外衣", rarity: "B", weight: 1.90 },
      { name: "軟軟羊耳罩", rarity: "B", weight: 1.80 },
      { name: "軟軟桃紅彩裙", rarity: "B", weight: 1.80 },
      { name: "軟軟粉紅靴子", rarity: "B", weight: 1.90 },
      { name: "軟軟叮噹披風", rarity: "B", weight: 1.90 },
      { name: "蜜蜂帽子", rarity: "C", weight: 4.88 },
      { name: "利堤帽子", rarity: "C", weight: 4.88 },
      { name: "鑽石名牌戒指", rarity: "C", weight: 4.88 },
      { name: "鑽石聊天戒指", rarity: "C", weight: 4.88 },
      { name: "球服", rarity: "C", weight: 4.88 },
      { name: "藍救生衣", rarity: "C", weight: 4.88 },
      { name: "心花怒放T恤", rarity: "C", weight: 4.88 },
      { name: "墨鏡白襯衫", rarity: "C", weight: 4.88 },
      { name: "藍色海洋連膝褲襪", rarity: "C", weight: 4.88 },
      { name: "仿舊天藍色牛仔褲", rarity: "C", weight: 4.88 },
      { name: "凱莉貓拖鞋", rarity: "C", weight: 4.88 },
      { name: "黑色木屐", rarity: "C", weight: 4.88 },
      { name: "噴射飛行推進器", rarity: "C", weight: 4.88 },
      { name: "彩色歡樂氣球", rarity: "C", weight: 4.88 },
      { name: "櫻花盛開時", rarity: "C", weight: 4.88 },
      { name: "我愛紅蘿蔔", rarity: "C", weight: 4.88 },
    ],
  },
  {
    id: "brilliant-comet",
    name: "璀璨彗星",
    period: "2026/08/27 09:00 ～ 2026/09/09 23:59",
    items: [
      { name: "血腥守護者帽", rarity: "S", weight: 1.10 },
      { name: "血腥新娘面紗", rarity: "S", weight: 1.10 },
      { name: "血腥守護者", rarity: "S", weight: 1.00 },
      { name: "血腥新娘", rarity: "S", weight: 1.00 },
      { name: "血腥中筒靴", rarity: "S", weight: 1.30 },
      { name: "血腥高跟鞋", rarity: "S", weight: 1.30 },
      { name: "血腥薔薇", rarity: "S", weight: 1.20 },
      { name: "血腥童話", rarity: "S", weight: 1.00 },
      { name: "黑暗音樂人耳機", rarity: "A", weight: 1.19 },
      { name: "黑暗音樂人套裝", rarity: "A", weight: 1.19 },
      { name: "黑暗音樂人披風", rarity: "A", weight: 1.31 },
      { name: "黑暗音樂人靴子", rarity: "A", weight: 1.38 },
      { name: "青春搖滾", rarity: "A", weight: 1.06 },
      { name: "超級之星M", rarity: "A", weight: 1.06 },
      { name: "獨裁者貝雷帽", rarity: "B", weight: 2.56 },
      { name: "獨裁者套服", rarity: "B", weight: 2.41 },
      { name: "施瓦茲靴子", rarity: "B", weight: 2.63 },
      { name: "獨裁者風衣", rarity: "B", weight: 2.56 },
      { name: "白兔髮夾", rarity: "B", weight: 2.56 },
      { name: "白兔禮服", rarity: "B", weight: 2.41 },
      { name: "白兔長靴", rarity: "B", weight: 2.63 },
      { name: "冷冽之痕", rarity: "A", weight: 1.13 },
      { name: "冷豔之心", rarity: "A", weight: 1.13 },
      { name: "冷豔之服", rarity: "A", weight: 1.13 },
      { name: "冷冽之服", rarity: "A", weight: 1.13 },
      { name: "冷豔的步伐", rarity: "A", weight: 1.19 },
      { name: "冷冽的步伐", rarity: "A", weight: 1.19 },
      { name: "冷冽的束縛", rarity: "A", weight: 1.06 },
      { name: "冷冽的希望", rarity: "B", weight: 0.94 },
      { name: "五顏六色冰淇淋", rarity: "B", weight: 2.50 },
      { name: "海上男人的海灘褲(男)／海灘辣妹的泳裝(女)", rarity: "B", weight: 2.50 },
      { name: "海上男人的夾腳拖(男)／海灘辣妹的夾腳拖(女)", rarity: "B", weight: 2.63 },
      { name: "枝仔冰", rarity: "B", weight: 2.50 },
      { name: "請給我冰淇淋", rarity: "B", weight: 2.44 },
      { name: "綠豬帽", rarity: "A", weight: 1.22 },
      { name: "可愛豬豬男生套組", rarity: "A", weight: 1.13 },
      { name: "可愛豬豬女生套組", rarity: "A", weight: 1.13 },
      { name: "可愛豬豬武器", rarity: "A", weight: 1.09 },
      { name: "寶貝貓咪帽", rarity: "B", weight: 2.50 },
      { name: "男生寶貝貓咪套裝", rarity: "B", weight: 2.47 },
      { name: "女生寶貝貓咪套裝", rarity: "B", weight: 2.47 },
      { name: "寶貝貓咪圍巾", rarity: "B", weight: 2.56 },
      { name: "喵嗚拳套", rarity: "B", weight: 2.63 },
      { name: "寶貝貓咪臉飾", rarity: "B", weight: 2.66 },
      { name: "寶貝貓咪鞋", rarity: "B", weight: 2.50 },
      { name: "雪月花•雪", rarity: "A", weight: 1.22 },
      { name: "雪月花•月", rarity: "A", weight: 1.06 },
      { name: "雪月花•花", rarity: "A", weight: 1.31 },
      { name: "白夜叉角", rarity: "A", weight: 1.13 },
      { name: "白夜叉套服", rarity: "A", weight: 1.06 },
      { name: "白夜叉斗篷", rarity: "A", weight: 1.16 },
      { name: "白夜叉木屐", rarity: "A", weight: 1.31 },
      { name: "白夜叉刺青", rarity: "A", weight: 1.22 },
      { name: "櫻花刀", rarity: "A", weight: 1.13 },
      { name: "過度沉迷者的帽子", rarity: "B", weight: 2.34 },
      { name: "過度沉迷者T恤", rarity: "B", weight: 2.25 },
      { name: "過度沉迷者褲", rarity: "B", weight: 2.25 },
      { name: "過度沉迷者書包", rarity: "B", weight: 2.63 },
      { name: "過度沉迷者鞋", rarity: "B", weight: 2.19 },
    ],
  },
  // 皇家美容院是「美髮券／整形券」各自獨立販售，男女、髮型/整形各是
  // 獨立一份 100% 機率表（不是合在一起抽），所以拆成 4 個獨立 box，
  // 不是 1 個 box 裡分 4 組
  {
    id: "royal-salon-hair-m",
    name: "皇家美容院・皇家美髮(男)",
    period: "2026/08/27 00:00 ～ 2026/09/09 23:59",
    items: [
      { name: "黑色俐落幻影造型", weight: 2.50 },
      { name: "黑色簡約瀏海造型", weight: 2.50 },
      { name: "黑色情歌王子造型", weight: 2.50 },
      { name: "黑色漂色造型", weight: 2.50 },
      { name: "黑色莉琳造型", weight: 7.50 },
      { name: "黑色層次柔順造型", weight: 7.50 },
      { name: "黑色個性大紮造型", weight: 7.50 },
      { name: "黑色雲朵造型", weight: 7.50 },
      { name: "黑色擴散鬃毛造型", weight: 15.00 },
      { name: "黑色側分飄逸造型", weight: 15.00 },
      { name: "黑色粗曠造型", weight: 15.00 },
      { name: "黑色街頭雅痞造型", weight: 15.00 },
    ],
  },
  {
    id: "royal-salon-hair-f",
    name: "皇家美容院・皇家美髮(女)",
    period: "2026/08/27 00:00 ～ 2026/09/09 23:59",
    items: [
      { name: "黑色捲馬尾造型", weight: 2.50 },
      { name: "黑色高音歌手造型", weight: 2.50 },
      { name: "黑色西洋栗造型", weight: 2.50 },
      { name: "黑色蝴蝶波浪造型", weight: 2.50 },
      { name: "黑色鞭炮辮子造型", weight: 7.50 },
      { name: "黑色雙色髮辮造型", weight: 7.50 },
      { name: "黑色妖精女王造型", weight: 7.50 },
      { name: "黑色甜姐兒造型", weight: 7.50 },
      { name: "黑色長髮娃娃造型", weight: 15.00 },
      { name: "黑色濃密澎澎造型", weight: 15.00 },
      { name: "黑色波希米亞造型", weight: 15.00 },
      { name: "黑色桃樂絲造型", weight: 15.00 },
    ],
  },
  {
    id: "royal-salon-face-m",
    name: "皇家美容院・皇家整形(男)",
    period: "2026/08/27 00:00 ～ 2026/09/09 23:59",
    items: [
      { name: "內向謹慎臉型", weight: 10.00 },
      { name: "奧妙的臉(男)", weight: 10.00 },
      { name: "瞭望的臉型", weight: 10.00 },
      { name: "懷疑的臉型", weight: 7.78 },
      { name: "堅決的臉型", weight: 7.78 },
      { name: "細長眼臉型", weight: 7.78 },
      { name: "很鎮定臉型", weight: 7.78 },
      { name: "好親切臉型", weight: 7.78 },
      { name: "翻白眼臉型", weight: 7.78 },
      { name: "夠性格臉型", weight: 7.78 },
      { name: "有自信臉型", weight: 7.78 },
      { name: "頗柔和臉型", weight: 7.78 },
    ],
  },
  {
    id: "royal-salon-face-f",
    name: "皇家美容院・皇家整形(女)",
    period: "2026/08/27 00:00 ～ 2026/09/09 23:59",
    items: [
      { name: "很搶眼臉型", weight: 10.00 },
      { name: "很妙的臉型", weight: 10.00 },
      { name: "瞭望的臉型", weight: 10.00 },
      { name: "好親切臉型", weight: 7.78 },
      { name: "夠性格臉型", weight: 7.78 },
      { name: "有自信臉型", weight: 7.78 },
      { name: "很叛逆臉型", weight: 7.78 },
      { name: "龍魔導士臉型", weight: 7.78 },
      { name: "好時髦臉型", weight: 7.78 },
      { name: "小眼睛臉型", weight: 7.78 },
      { name: "懷疑的臉型", weight: 7.78 },
      { name: "丹鳳眼臉型", weight: 7.78 },
    ],
  },
  // 官方頁面上這台的名稱就叫「轉蛋機」（不像閃亮彗星/璀璨彗星有主題名），
  // 道具是家具/變身藥水/擴充券這類雜項，不分 S/A/B/C 稀有度分級——官方
  // 表格本身就沒有分級欄位，所以這箱的 items 不帶 rarity（跟皇家美容院
  // 那幾箱一樣，gacha.js 對沒有 rarity 的道具本來就有處理）
  {
    id: "gasha-machine",
    name: "轉蛋機",
    period: "2026/08/20 09:00 ～ 2026/09/10 00:00",
    items: [
      { name: "蘑菇友情椅子", weight: 1.00 },
      { name: "玫瑰椅", weight: 1.00 },
      { name: "紅色設計師椅", weight: 1.00 },
      { name: "綠色設計師椅", weight: 1.00 },
      { name: "木妖橡皮擦", weight: 0.35 },
      { name: "蘑菇王橡皮擦", weight: 0.35 },
      { name: "猴子橡皮擦", weight: 0.35 },
      { name: "大幽靈橡皮擦", weight: 0.35 },
      { name: "綠水靈橡皮擦", weight: 0.35 },
      { name: "三眼章魚橡皮擦", weight: 0.35 },
      { name: "六角水晶項鍊", weight: 0.35 },
      { name: "水女神的衣料", weight: 0.35 },
      { name: "黑之包", weight: 0.94 },
      { name: "10個能力點數重配卷軸交換券", weight: 0.67 },
      { name: "10個一轉技能點數重配卷軸交換券", weight: 0.67 },
      { name: "二轉技能點數重配卷軸5個交換券", weight: 0.67 },
      { name: "瞬移之石交換券", weight: 0.50 },
      { name: "裝備欄8格擴充券", weight: 0.50 },
      { name: "消耗欄8格擴充券", weight: 0.50 },
      { name: "裝飾欄8格擴充券", weight: 0.50 },
      { name: "其他欄8格擴充券", weight: 0.50 },
      { name: "寵物速度卷軸100%", weight: 0.58 },
      { name: "套服防禦卷軸100%", weight: 0.58 },
      { name: "褲、裙防禦卷軸100%", weight: 0.58 },
      { name: "鞋子敏捷卷軸100%", weight: 0.58 },
      { name: "手套敏捷卷軸100%", weight: 0.58 },
      { name: "盾牌防禦卷軸100%", weight: 0.58 },
      { name: "披風魔防卷軸100%", weight: 0.58 },
      { name: "披風防禦卷軸100%", weight: 0.58 },
      { name: "披風生命卷軸100%", weight: 0.58 },
      { name: "披風魔力卷軸100%", weight: 0.58 },
      { name: "單手劍攻擊卷軸100%", weight: 0.58 },
      { name: "單手斧攻擊卷軸100%", weight: 0.58 },
      { name: "單手棍攻擊卷軸100%", weight: 0.58 },
      { name: "短劍攻擊卷軸100%", weight: 0.58 },
      { name: "短杖魔力卷軸100%", weight: 0.58 },
      { name: "長杖魔力卷軸100%", weight: 0.58 },
      { name: "雙手劍攻擊卷軸100%", weight: 0.58 },
      { name: "雙手斧攻擊卷軸100%", weight: 0.58 },
      { name: "雙手棍攻擊卷軸100%", weight: 0.58 },
      { name: "槍攻擊卷軸100%", weight: 0.58 },
      { name: "矛攻擊卷軸100%", weight: 0.58 },
      { name: "弓攻擊卷軸100%", weight: 0.58 },
      { name: "弩攻擊卷軸100%", weight: 0.58 },
      { name: "拳套攻擊卷軸100%", weight: 0.58 },
      { name: "指虎攻擊卷軸100%", weight: 0.58 },
      { name: "火槍攻擊卷軸100%", weight: 0.58 },
      { name: "寵物跳躍力卷軸100%", weight: 0.58 },
      { name: "雪人變身藥水", weight: 0.90 },
      { name: "蘑菇王變身藥水", weight: 0.90 },
      { name: "超級綠水靈變身藥水", weight: 0.90 },
      { name: "巴洛古變身藥水", weight: 0.90 },
      { name: "菇菇寶貝的雕像", weight: 0.90 },
      { name: "緞帶肥肥的雕像", weight: 0.90 },
      { name: "斧木妖變身藥水", weight: 0.90 },
      { name: "綠水靈變身藥水", weight: 0.90 },
      { name: "殭屍菇菇變身！", weight: 0.90 },
      { name: "天使猴變身！", weight: 0.90 },
      { name: "大幽靈變身！", weight: 0.90 },
      { name: "頭暈目眩交換券", weight: 1.48 },
      { name: "氣喘吁吁交換券", weight: 1.48 },
      { name: "嘎嗚交換券", weight: 1.48 },
      { name: "親親交換券", weight: 1.48 },
      { name: "眨眼交換券", weight: 1.48 },
      { name: "淚痕交換券", weight: 1.48 },
      { name: "閃閃發光交換券", weight: 1.48 },
      { name: "嘩嘩交換券", weight: 1.48 },
      { name: "閃閃發亮交換券", weight: 1.48 },
      { name: "噗交換券", weight: 1.48 },
      { name: "呵哈呵哈交換券", weight: 1.48 },
      { name: "哼嗯交換券", weight: 1.48 },
      { name: "點頭瞌睡交換券", weight: 1.48 },
      { name: "啊好燙交換券", weight: 1.48 },
      { name: "吐舌頭交換券", weight: 1.48 },
      { name: "微笑太陽交換券", weight: 1.48 },
      { name: "閃閃星月交換券", weight: 1.48 },
      { name: "七色彩虹交換券", weight: 1.48 },
      { name: "魔女莉莉交換券", weight: 1.48 },
      { name: "潛水中交換券", weight: 1.48 },
      { name: "戀愛心願交換券", weight: 1.48 },
      { name: "守護天使交換券", weight: 1.48 },
      { name: "懸賞海報交換券", weight: 1.48 },
      { name: "一起玩吧交換券", weight: 1.48 },
      { name: "我要自己玩交換券", weight: 1.48 },
      { name: "烏雲交換券", weight: 1.48 },
      { name: "星星交換券", weight: 1.48 },
      { name: "微笑交換券", weight: 1.48 },
      { name: "愛心交換券", weight: 1.48 },
      { name: "閃耀之星特效交換券", weight: 1.48 },
      { name: "對你心動特效交換券", weight: 1.48 },
      { name: "玩具小鴨家族交換券", weight: 1.48 },
      { name: "火冒三丈交換券", weight: 1.48 },
      { name: "我的男友交換券", weight: 1.48 },
      { name: "我的女友交換券", weight: 1.48 },
      { name: "抖抖抖交換券", weight: 1.48 },
      { name: "撥水柱特效交換券", weight: 1.48 },
      { name: "聚光燈交換券", weight: 1.48 },
      { name: "啦啦啦音符交換券", weight: 1.48 },
      { name: "眼光交換券", weight: 1.48 },
      { name: "天打雷劈交換券", weight: 1.48 },
      { name: "花精靈交換券", weight: 1.48 },
    ],
  },
];

window.MapleGachaBoxes = GACHA_BOXES;
